using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraBars;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using DataLibrary.BUS;
using DataLibrary.DTO;
using QLTuyenDungApp.XuLyHoSo;

namespace QLTuyenDungApp.XuLyHoSo
{
    public partial class frmCapNhapKQPV : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        private List<tbl_HoSoPV> list = new List<tbl_HoSoPV>();
        public frmCapNhapKQPV()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DataLibrary.DTO.TuyenDungModels dbContext = new DataLibrary.DTO.TuyenDungModels();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.tbl_HoSoPV.Load();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_HoSoPVBindingSource.DataSource = dbContext.tbl_HoSoPV.Local.ToBindingList();
        }
        private void LoadData()
        {
            this.list = HoSoPVBUS.Instance.GetAllData();
            var bindingList = new BindingList<tbl_HoSoPV>(list);
            var source = new BindingSource(bindingList, null);
            tbl_HoSoPVBindingSource.DataSource = source;
        }
        private void gridView1_DoubleClick(object sender, EventArgs e)
        {
            if (list[gridView1.GetSelectedRows()[0]].NgayPV == null)
            {
                frmDatLichPV frm = new frmDatLichPV(list[gridView1.GetSelectedRows()[0]].NhanVienID ?? default(int));
                frm.ShowDialog();
                LoadData();
            }
            else
            {
                frmKQHoSoPV frm = new frmKQHoSoPV(list[gridView1.GetSelectedRows()[0]].NhanVienID ?? default(int));
                frm.ShowDialog();
                LoadData();
            }
        }

        private void bbiResult_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (list[gridView1.GetSelectedRows()[0]].NgayPV != null)
            {
                frmKQHoSoPV frm = new frmKQHoSoPV(list[gridView1.GetSelectedRows()[0]].HoSoPVID);
                frm.ShowDialog();
                LoadData();
            }
            else
            {
                XtraMessageBox.Show("Chưa đặt lịch", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
        private void bbiSetDate_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (list[gridView1.GetSelectedRows()[0]].KetQuaPV == null)
            {
                frmDatLichPV frm = new frmDatLichPV(list[gridView1.GetSelectedRows()[0]].HoSoPVID);
                frm.ShowDialog();
                LoadData();
            } else
            {
                XtraMessageBox.Show("Đã phỏng vấn", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
        private void frmCapNhapKQPV_Load(object sender, EventArgs e)
        {
            LoadData();
        }

        private void bbiRefresh_ItemClick(object sender, ItemClickEventArgs e)
        {
            LoadData();
        }
    }
}