using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DataLibrary.BUS;
using DataLibrary.DTO;
using System.Data.Entity;

namespace QLTuyenDungApp.ThongBao
{
    public partial class frmThongBao : DevExpress.XtraEditors.XtraForm
    {
        private List<tbl_MauThongBao> list = new List<tbl_MauThongBao>();
        public frmThongBao()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DataLibrary.DTO.TuyenDungModels dbContext = new DataLibrary.DTO.TuyenDungModels();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.tbl_MauThongBao.Load();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_MauThongBaoBindingSource.DataSource = dbContext.tbl_MauThongBao.Local.ToBindingList();
        }
        private void LoadData()
        {
            this.list = MauThongBaoBUS.Instance.GetAllData();
            var bindingList = new BindingList<tbl_MauThongBao>(list);
            var source = new BindingSource(bindingList, null);
            tbl_MauThongBaoBindingSource.DataSource = source;
        }
        private void frmThongBao_Load(object sender, EventArgs e)
        {
            LoadData();
        }

        private void bntThoat_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void bntThem_Click(object sender, EventArgs e)
        {
            frmChiTietMauBaoCao frm = new frmChiTietMauBaoCao();
            frm.ShowDialog();
            LoadData();
        }

        private void bntXoa_Click(object sender, EventArgs e)
        {
            if (XtraMessageBox.Show("Bạn có chắc chắn muốn xóa không?", "Cảnh báo!", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
                MauThongBaoBUS.Instance.DeleteData(list[gridView1.GetSelectedRows()[0]].ThongBaoID);
            LoadData();
        }
        private void gridView1_DoubleClick(object sender, EventArgs e)
        {
            frmChiTietMauBaoCao frm = new frmChiTietMauBaoCao(list[gridView1.GetSelectedRows()[0]].ThongBaoID);
            frm.ShowDialog();
            LoadData();
        }
    }
}