using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraBars;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using DataLibrary.BUS;
using DataLibrary.DTO;

namespace QLTuyenDungApp.CapNhapTinhHinh
{
    public partial class frmCapNhap : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        private int _id;
        private List<tbl_TinhHinhThuViec> list = new List<tbl_TinhHinhThuViec>();
        private tbl_ThuViec _tv = new tbl_ThuViec();
        private tbl_NhanVien _hs = new tbl_NhanVien();
        public frmCapNhap()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DataLibrary.DTO.TuyenDungModels dbContext = new DataLibrary.DTO.TuyenDungModels();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.tbl_TinhHinhThuViec.Load();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_TinhHinhThuViecBindingSource.DataSource = dbContext.tbl_TinhHinhThuViec.Local.ToBindingList();
        }
        public frmCapNhap(int id)
        {
            InitializeComponent();
            DataLibrary.DTO.TuyenDungModels dbContext = new DataLibrary.DTO.TuyenDungModels();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.tbl_TinhHinhThuViec.Load();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_TinhHinhThuViecBindingSource.DataSource = dbContext.tbl_TinhHinhThuViec.Local.ToBindingList();
            _id = id;
            Init();
            LoadData();
        }
        private void Init()
        {
            _tv = ThuViecBUS.Instance.GetOneData(_id);
            _hs = NhanVienBUS.Instance.GetOneData(_tv.ThuViecID);
            txtTen.Caption = _hs.HoTen;
            bbiGT.Caption = (_hs.GioiTinh ?? default(bool)) ? "Nam" : "Nữ";
        }
        private void LoadData()
        {
            this.list = TinhHinhThuViecBUS.Instance.GetAllDataByTVID(_tv.ThuViecID);
            if(list == null)
            {
                XtraMessageBox.Show("Tải dữ liệu lỗi", "Thông báo lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error); ;
            }
            var bindingList = new BindingList<tbl_TinhHinhThuViec>(list);
            var source = new BindingSource(bindingList, null);
            tbl_TinhHinhThuViecBindingSource.DataSource = source;
        }
        private void bbiRefresh_ItemClick(object sender, ItemClickEventArgs e)
        {
            LoadData();
        }

        private void bbiEdit_ItemClick(object sender, ItemClickEventArgs e)
        {
            if(gridView.SelectedRowsCount > 0)
            {
                frmThemTinhHinh frm = new frmThemTinhHinh(_tv.ThuViecID, list[gridView.GetSelectedRows()[0]].TinhHinhThuViecID);
                frm.ShowDialog();
                LoadData();
            }
        }

        private void bbiNew_ItemClick(object sender, ItemClickEventArgs e)
        {
            frmThemTinhHinh frm = new frmThemTinhHinh(_tv.ThuViecID);
            frm.ShowDialog();
            LoadData();
        }

        private void bbiDelete_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (gridView.SelectedRowsCount > 0)
            {
                if(XtraMessageBox.Show("Bạn có chắc chắn muốn xóa không?", "Cảnh báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                {
                    TinhHinhThuViecBUS.Instance.DeleteData(list[gridView.GetSelectedRows()[0]].TinhHinhThuViecID);
                    LoadData();
                }
            }
        }

        private void gridView_DoubleClick(object sender, EventArgs e)
        {
            if (gridView.SelectedRowsCount > 0)
            {
                frmThemTinhHinh frm = new frmThemTinhHinh(_tv.ThuViecID, list[gridView.GetSelectedRows()[0]].TinhHinhThuViecID);
                frm.ShowDialog();
                LoadData();
            }
        }
    }
}