using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraBars;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using DataLibrary.DTO;
using DataLibrary.BUS;

namespace QLTuyenDungApp.CapNhapTinhHinh
{
    public partial class frmTinhHinh : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        private List<tbl_ThuViec> list = new List<tbl_ThuViec>();
        public frmTinhHinh()
        {
            InitializeComponent();
            DataLibrary.DTO.TuyenDungModels dbContext = new DataLibrary.DTO.TuyenDungModels();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.tbl_ThuViec.Load();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_ThuViecBindingSource.DataSource = dbContext.tbl_ThuViec.Local.ToBindingList();
        }
        private void LoadData()
        {
            this.list = ThuViecBUS.Instance.GetAllData();
            var bindingList = new BindingList<tbl_ThuViec>(list);
            var source = new BindingSource(bindingList, null);
            tbl_ThuViecBindingSource.DataSource = source;
        }
        private void bbiDatThoiGian_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (list[gridView1.GetSelectedRows()[0]].NgayThuViec > DateTime.Now)
            {
                XtraMessageBox.Show("Đã vào thời gian thử việc", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            else
            {
                frmDatLich frm = new frmDatLich(list[gridView1.GetSelectedRows()[0]].ThuViecID);
                frm.ShowDialog();
                LoadData();
            }
        }

        private void frmTinhHinh_Load(object sender, EventArgs e)
        {
            LoadData();
        }

        private void gridView_DoubleClick(object sender, EventArgs e)
        {
            if(list[gridView1.GetSelectedRows()[0]].NgayThuViec == null)
            {
                frmDatLich frm = new frmDatLich(list[gridView1.GetSelectedRows()[0]].ThuViecID);
                frm.ShowDialog();
                LoadData();
            }
            else if(list[gridView1.GetSelectedRows()[0]].NgayThuViec >= DateTime.Now.AddDays(-1))
            {
                frmCapNhap frm = new frmCapNhap(list[gridView1.GetSelectedRows()[0]].ThuViecID);
                frm.ShowDialog();
                LoadData();
            }
            else
            {
                XtraMessageBox.Show("Tuyển sinh vẫn chưa vào giai đoạn thử việc", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void bbiRefresh_ItemClick(object sender, ItemClickEventArgs e)
        {
            LoadData();
        }

        private void bbiCapNhap_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (list[gridView1.GetSelectedRows()[0]].NgayThuViec == null || list[gridView1.GetSelectedRows()[0]].NgayThuViec < DateTime.Now.AddDays(-1))
            {
                XtraMessageBox.Show("Tuyển sinh vẫn chưa vào giai đoạn thử việc", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            else
            {
                frmCapNhap frm = new frmCapNhap(list[gridView1.GetSelectedRows()[0]].ThuViecID);
                frm.ShowDialog();
                LoadData();
            }
        }

        private void bbiChapNhan_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (list[gridView1.GetSelectedRows()[0]].NgayKetThucThuViec <= DateTime.Now)
            {
                if(XtraMessageBox.Show("Bạn có chắc chắn nhận không?", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                {
                    tbl_NhanVien _hs = NhanVienBUS.Instance.GetOneData(list[gridView1.GetSelectedRows()[0]].NhanVienID ?? default(int));
                    _hs.TrangThai = 5;
                    NhanVienBUS.Instance.UpdateData(_hs);
                    LoadData();
                }
            }
            else
            {
                XtraMessageBox.Show("Thử việc vẫn chưa kết thúc", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void bbiKhongChapNhan_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (list[gridView1.GetSelectedRows()[0]].NgayKetThucThuViec <= DateTime.Now)
            {
                if (XtraMessageBox.Show("Bạn có chắc từ chối không?", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                {
                    tbl_NhanVien _hs = NhanVienBUS.Instance.GetOneData(list[gridView1.GetSelectedRows()[0]].NhanVienID ?? default(int));
                    _hs.TrangThai = -1;
                    NhanVienBUS.Instance.UpdateData(_hs);
                    LoadData();
                }
            }
            else
            {
                XtraMessageBox.Show("Thử việc vẫn chưa kết thúc", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
    }
}