using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraBars;
using System.ComponentModel.DataAnnotations;
using DataLibrary.BUS;
using DataLibrary.DTO;
using System.Data.Entity;

namespace QLTuyenDungApp.BaoCao
{
    public partial class frmBaoCao : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        private int id = 1;
        public frmBaoCao()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DataLibrary.DTO.TuyenDungModels dbContext = new DataLibrary.DTO.TuyenDungModels();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.tbl_NhanVien.Load();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_NhanVienBindingSource.DataSource = dbContext.tbl_NhanVien.Local.ToBindingList();
        }
        void bbiPrintPreview_ItemClick(object sender, ItemClickEventArgs e)
        {
            gridControl.ShowRibbonPrintPreview();
        }
        private void LoadData()
        {
            switch (id)
            {
                case 1:
                    {
                        List<tbl_NhanVien> list = NhanVienBUS.Instance.GetAllDataSortByViTri();
                        var bindingList = new BindingList<tbl_NhanVien>(list);
                        var source = new BindingSource(bindingList, null);
                        tbl_NhanVienBindingSource.DataSource = source;
                        break;
                    }
                case 2:
                    {
                        List<tbl_NhanVien> list = NhanVienBUS.Instance.GetAllDataSortByPhongBan();
                        var bindingList = new BindingList<tbl_NhanVien>(list);
                        var source = new BindingSource(bindingList, null);
                        tbl_NhanVienBindingSource.DataSource = source;
                        break;
                    }
                case 3:
                    {
                        List<tbl_NhanVien> list = NhanVienBUS.Instance.GetAllDataSortByChuyenMon();
                        var bindingList = new BindingList<tbl_NhanVien>(list);
                        var source = new BindingSource(bindingList, null);
                        tbl_NhanVienBindingSource.DataSource = source;
                        break;
                    }
                case 4:
                    {
                        List<tbl_NhanVien> list = NhanVienBUS.Instance.GetAllDataSortByChuyenMon();
                        var bindingList = new BindingList<tbl_NhanVien>(list);
                        var source = new BindingSource(bindingList, null);
                        break;
                    }
                case 5:
                    {
                        List<tbl_NhanVien> list = NhanVienBUS.Instance.GetAllDataSortByViTri();
                        var bindingList = new BindingList<tbl_NhanVien>(list);
                        var source = new BindingSource(bindingList, null);
                        tbl_NhanVienBindingSource.DataSource = source;
                        break;
                    }
            }
        }
        private void bbiRefresh_ItemClick(object sender, ItemClickEventArgs e)
        {
            LoadData();
        }

        private void bbiViTri_ItemClick(object sender, ItemClickEventArgs e)
        {
            id = 1;
            LoadData();
        }

        private void bbiPhongBan_ItemClick(object sender, ItemClickEventArgs e)
        {
            id = 2;
            LoadData();
        }

        private void bbiCM_ItemClick(object sender, ItemClickEventArgs e)
        {
            id = 3;
            LoadData();
        }

        private void bbKhaNang_ItemClick(object sender, ItemClickEventArgs e)
        {
            id = 4;
            LoadData();
        }

        private void bbiHoSo_ItemClick(object sender, ItemClickEventArgs e)
        {
            id = 5;
            LoadData();
        }
    }
}